export const ACTIVITY_RATING = 'ACTIVITY_RATING';
export const ACTIVITY_MODAL_RATING = 'ACTIVITY_MODAL_RATING';
export const ACTIVITY_MODAL = 'ACTIVITY_MODAL';
export const ACTIVITY_VIEW_RATING = 'ACTIVITY_VIEW_RATING';
export const ACTIVITY_TUTORIAL = 'ACTIVITY_TUTORIAL';
export const ACTIVITY_TRAINING_SELECT = 'ACTIVITY_TRAINING_SELECT';
export const ACTIVITY_DATE_DETAIL = 'ACTIVITY_DATE_DETAIL';
export const ACTIVITY_PERCENTAGE = 'ACTIVITY_PERCENTAGE';