export const FLUSH_TUTORIAL = 'FLUSH_TUTORIAL';
export const FLUSH_TEXT = 'FLUSH_TEXT';
export const FLUSH_TYPE_RESOURCE = 'FLUSH_TYPE_RESOURCE';
export const FLUSH_RESOURCE = 'FLUSH_RESOURCE';
export const FLUSH_ENTRIES = 'FLUSH_ENTRIES';
export const FLUSH_BREATHE = 'FLUSH_BREATHE';
export const FLUSH_CLEAR = 'FLUSH_CLEAR';