export const PURCHASES_RESQUEST_STATUS = 'PURCHASES_RESQUEST_STATUS';
export const PURCHASES_STATUS = 'PURCHASES_STATUS';
export const PURCHASES_ITEMS_IOS = 'PURCHASES_ITEMS_IOS';
export const PURCHASES_SELECTED = 'PURCHASES_SELECTED';
export const PURCHASES_HISTORIAL = 'PURCHASES_HISTORIAL';