export const USER_SHARE_DETAIL = 'USER_SHARE_DETAIL';
export const USER_SHARE_ACTION = 'USER_SHARE_ACTION';
export const USER_SHARE_LIST = 'USER_SHARE_LIST';
export const USER_SHARE_SELECTED = 'USER_SHARE_SELECTED';
export const USER_SHARE_LOADING = 'USER_SHARE_LOADING';
export const USER_SHARE_VISIBLE = 'USER_SHARE_VISIBLE';
export const USER_SHARE_SEARCH = 'USER_SHARE_SEARCH';
export const USER_SHARE_CLEAR = 'USER_SHARE_CLEAR';